### ISSUE TITLE
Try to file stream with raw data 2p nwb

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#30] opened 2022-10-27 18:56 UTC
Once @Ahad-Allen uploads a 2p raw data file, we should try to see if this is a good use case for file streaming, or if some other system would be better. Additionally, we'll see if nwbwidget works for viewing these data or if we have to work on a way to view the video data.

**Comment by rcpeene** [comment] 2022-11-03 21:09
Waiting on Ahad to generate new files with valid raw data in them. Should be done soon.

**Comment by jeromelecoq** [comment] 2022-11-07 19:27
This is a duplicate of #54

**Closed by jeromelecoq** 2022-11-07 19:27 UTC
Labels: enhancement
